services:
  - type: web
    name: bookmyshow13
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn bookmyseat.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookmyseat.settings
      - key: PYTHON_VERSION
        value: 3.12.3
