services:
  - type: web
    name: bookmyshow13
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && python manage.py collectstatic --noinput && gunicorn bookmyshow13copy2.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookmyshow13 - copy (2).settings
      - key: PYTHON_VERSION
        value: 3.12.3
