# Generated by Django 3.2.19 on 2025-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='showtime',
            name='show_date',
            field=models.DateField(default='2025-06-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='show_time',
            field=models.TimeField(default='18:00:00'),
            preserve_default=False,
        ),
    ]
