# Generated by Django 3.2.19 on 2025-06-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20250617_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.showtime'),
        ),
    ]
