# Generated by Django 3.2.19 on 2025-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20250619_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(default='Action', max_length=100),
            preserve_default=False,
        ),
    ]
