# Generated by Django 3.2.19 on 2025-06-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Action', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
